# This is a basic workflow to help you get started with Actions

name: getting started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo show directory
          ls -la
          echo
          echo java version
          java -version
          echo
          echo is git installed?
          git --version
          echo
          echo tell me maven version
          mvn --version
          echo where is android SDK root?
          echo $ANDROID_SDK_ROOT
          echo
          location of Selenium jars
          echo $SELENIUM_JAR_PATH
          echo
          echo Availabl ENV variables
          env
          echo who is runing this scrpt?
          whoami
          echo How is the disc laid out?
          df
          echo Location of workspace
          echo $RUNNER_WORKSPACE
          echo
          echo How is the disc laid out?
          df
          echo Availabl ENV variables
          env
          
          echo test, and deploy your project.
